# Generated by Django 4.2.21 on 2025-08-19 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='user.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
