# Generated by Django 4.2.21 on 2025-08-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_organization_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='created_by',
        ),
    ]
